
  
  const withDefaults = (p) => ({
    currency: "AZN",
    status: "active",
    stock: 5,
    ram: "",
    storage: "",
    ...p,
  });
  
  const products = [
    withDefaults({
      id: 1,
      name: "iPhone 13",
      slug: "iphone-13",
      brand: "Apple",
      category: "iPhone",
      condition: "new",
      price: 1399,
      oldPrice: 1599,
      warranty: "1 il zəmanət",
      stock: 8,
      ram: "4GB",
      storage: "128GB",
      shortDescription: "128GB, Midnight. Orijinal, sızdırılmamış qutuda.",
      fullDescription:
        "iPhone 13 orijinal məhsuldur, premium vəziyyətdə təqdim olunur. Gündəlik istifadə, iş və content üçün ideal seçimdir.",
      specifications: {
        Yaddaş: "128GB",
        RAM: "4GB",
        Ekran: '6.1"',
        Kamera: "12MP",
      },
      featured: true,
      popular: true,
      mainImage: images.https://kontakt.az/media/catalog/product/cache/9401ea41f0a7055d2fa261226a20793b/t/m/tm-dg-sbp-1105-sm-1510_12.png,
      gallery: images.https://kontakt.az/media/catalog/product/cache/9401ea41f0a7055d2fa261226a20793b/t/m/tm-dg-sbp-1105-sm-1510_44.png,
      createdAt: "2025-02-10",
    }),
    withDefaults({
      id: 2,
      name: "iPhone 14 Pro",
      slug: "iphone-14-pro",
      brand: "Apple",
      category: "iPhone",
      condition: "new",
      price: 1999,
      oldPrice: 2199,
      warranty: "1 il zəmanət",
      stock: 4,
      ram: "6GB",
      storage: "256GB",
      shortDescription: "256GB, Deep Purple. Pro ekran, güclü kamera.",
      fullDescription:
        "iPhone 14 Pro qabaqcıl kamera sistemi, güclü performans və premium dizayn istəyənlər üçün nəzərdə tutulub.",
      specifications: {
        Yaddaş: "256GB",
        RAM: "6GB",
        Ekran: '6.7"',
        Kamera: "48MP",
      },
      featured: true,
      popular: true,
      mainImage: images.iphone[1],
      gallery: images.iphone,
      createdAt: "2025-03-18",
    }),
    withDefaults({
      id: 3,
      name: "iPhone 11 İşlənmiş",
      slug: "iphone-11-used",
      brand: "Apple",
      category: "iPhone",
      condition: "used",
      price: 699,
      oldPrice: 799,
      warranty: "1 il zəmanət",
      stock: 3,
      ram: "4GB",
      storage: "64GB",
      shortDescription:
        "Yoxlanılmış işlənmiş model, gündəlik istifadə üçün ideal.",
      fullDescription:
        "İşlənmiş iPhone 11 bütün əsas funksiyaları yoxlanmış şəkildə təklif olunur.",
      specifications: {
        Yaddaş: "64GB",
        RAM: "4GB",
        Ekran: '6.1"',
        Vəziyyət: "Yoxlanılıb",
      },
      featured: false,
      popular: true,
      mainImage: images.iphone[0],
      gallery: images.iphone,
      createdAt: "2025-01-12",
    }),
    withDefaults({
      id: 4,
      name: "Samsung Galaxy S23",
      slug: "samsung-galaxy-s23",
      brand: "Samsung",
      category: "Samsung",
      condition: "new",
      price: 1699,
      oldPrice: 1899,
      warranty: "1 il zəmanət",
      stock: 6,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "256GB, flagship Android təcrübəsi.",
      fullDescription:
        "Samsung Galaxy S23 sürətli performans, müasir kamera sistemi və zərif dizaynı ilə premium seçimdir.",
      specifications: {
        Yaddaş: "256GB",
        RAM: "8GB",
        Ekran: '6.1"',
        Kamera: "50MP",
      },
      featured: true,
      popular: true,
      mainImage: images.samsung[0],
      gallery: images.samsung,
      createdAt: "2025-03-01",
    }),
    withDefaults({
      id: 5,
      name: "Samsung Galaxy A54",
      slug: "samsung-galaxy-a54",
      brand: "Samsung",
      category: "Samsung",
      condition: "new",
      price: 999,
      oldPrice: 1099,
      warranty: "1 il zəmanət",
      stock: 7,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Balanslı orta sinif, premium ekran.",
      fullDescription:
        "Samsung A54 gündəlik istifadə, sosial media və iş üçün çox balanslı bir modeldir.",
      specifications: {
        Yaddaş: "256GB",
        RAM: "8GB",
        Ekran: '6.4"',
        Kamera: "50MP",
      },
      featured: false,
      popular: true,
      mainImage: images.samsung[1],
      gallery: images.samsung,
      createdAt: "2025-02-26",
    }),
    withDefaults({
      id: 6,
      name: "Samsung S21 İşlənmiş",
      slug: "samsung-s21-used",
      brand: "Samsung",
      category: "Samsung",
      condition: "used",
      price: 799,
      oldPrice: 899,
      warranty: "1 il zəmanət",
      stock: 2,
      ram: "8GB",
      storage: "128GB",
      shortDescription: "Güclü kamera və ekranla yoxlanılmış işlənmiş model.",
      fullDescription:
        "İşlənmiş Samsung S21 texniki yoxlanışdan keçmiş, istifadəyə hazır vəziyyətdə.",
      specifications: {
        Yaddaş: "128GB",
        RAM: "8GB",
        Ekran: '6.2"',
        Vəziyyət: "Yoxlanılıb",
      },
      featured: false,
      popular: true,
      mainImage: images.samsung[0],
      gallery: images.samsung,
      createdAt: "2025-01-20",
    }),
    withDefaults({
      id: 7,
      name: "Redmi Note 13",
      slug: "redmi-note-13",
      brand: "Redmi",
      category: "Redmi",
      condition: "new",
      price: 599,
      oldPrice: 699,
      warranty: "1 il zəmanət",
      stock: 10,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Qiymət-keyfiyyət nisbətinə görə ən yaxşı seçim.",
      fullDescription:
        "Redmi Note 13 büdcə dostu, amma funksional telefon axtaranlar üçün ən yaxşı seçimdir.",
      specifications: {
        Yaddaş: "256GB",
        RAM: "8GB",
        Ekran: '6.67"',
        Kamera: "108MP",
      },
      featured: true,
      popular: true,
      mainImage: images.redmi[0],
      gallery: images.redmi,
      createdAt: "2025-03-08",
    }),
    withDefaults({
      id: 8,
      name: "Redmi 12",
      slug: "redmi-12",
      brand: "Redmi",
      category: "Redmi",
      condition: "new",
      price: 449,
      oldPrice: 499,
      warranty: "1 il zəmanət",
      stock: 9,
      ram: "4GB",
      storage: "128GB",
      shortDescription: "Gündəlik istifadə üçün sadə, etibarlı telefon.",
      fullDescription:
        "Redmi 12 gündəlik zəng, sosial media və sadə istifadə üçün rahat modeldir.",
      specifications: {
        Yaddaş: "128GB",
        RAM: "4GB",
        Ekran: '6.5"',
        Kamera: "50MP",
      },
      featured: false,
      popular: false,
      mainImage: images.redmi[1],
      gallery: images.redmi,
      createdAt: "2025-03-02",
    }),
    withDefaults({
      id: 9,
      name: "Redmi Note 11 İşlənmiş",
      slug: "redmi-note-11-used",
      brand: "Redmi",
      category: "Redmi",
      condition: "used",
      price: 299,
      oldPrice: 349,
      warranty: "1 il zəmanət",
      stock: 4,
      ram: "4GB",
      storage: "64GB",
      shortDescription: "Büdcəli işlənmiş model, yoxlanılmış vəziyyətdə.",
      fullDescription:
        "İşlənmiş Redmi Note 11 yoxlanılmış və istifadəyə hazır vəziyyətdə.",
      specifications: {
        Yaddaş: "64GB",
        RAM: "4GB",
        Ekran: '6.5"',
        Vəziyyət: "Yoxlanılıb",
      },
      featured: false,
      popular: false,
      mainImage: images.redmi[0],
      gallery: images.redmi,
      createdAt: "2025-01-05",
    }),
    withDefaults({
      id: 10,
      name: "Dyson Airwrap",
      slug: "dyson-airwrap",
      brand: "Dyson",
      category: "Dyson",
      condition: "new",
      price: 1299,
      oldPrice: 1499,
      warranty: "1 il zəmanət",
      stock: 5,
      ram: "",
      storage: "",
      shortDescription: "Premium saç formalaşdırma cihazı.",
      fullDescription:
        "Dyson Airwrap premium saç formalaşdırma cihazıdır, orijinal məhsul kimi təqdim olunur.",
      specifications: { Güc: "1300W", Rejimlər: "Çoxsəviyyəli", Zəmanət: "1 il" },
      featured: true,
      popular: true,
      mainImage: images.dyson[0],
      gallery: images.dyson,
      createdAt: "2025-03-15",
    }),
    withDefaults({
      id: 11,
      name: "Dyson V15",
      slug: "dyson-v15",
      brand: "Dyson",
      category: "Dyson",
      condition: "new",
      price: 1599,
      oldPrice: 1799,
      warranty: "1 il zəmanət",
      stock: 3,
      ram: "",
      storage: "",
      shortDescription: "Premium simsiz tozsoran.",
      fullDescription: "Dyson V15 yüksək gücə malik simsiz tozsorandır.",
      specifications: { Güc: "545W", Filtr: "HEPA", Zəmanət: "1 il" },
      featured: true,
      popular: false,
      mainImage: images.dyson[1],
      gallery: images.dyson,
      createdAt: "2025-03-14",
    }),
    withDefaults({
      id: 12,
      name: "iPad Air",
      slug: "ipad-air",
      brand: "Apple",
      category: "iPad",
      condition: "new",
      price: 1299,
      oldPrice: 1399,
      warranty: "1 il zəmanət",
      stock: 6,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Yüngül planşet, iş, təhsil və content üçün.",
      fullDescription:
        "iPad Air məhsuldarlıq, təhsil və gündəlik multimedia istifadəsi üçün ideal balansdır.",
      specifications: { Yaddaş: "256GB", RAM: "8GB", Ekran: '10.9"', Chip: "M1" },
      featured: true,
      popular: true,
      mainImage: images.ipad[0],
      gallery: images.ipad,
      createdAt: "2025-02-20",
    }),
    withDefaults({
      id: 13,
      name: "iPad Pro",
      slug: "ipad-pro",
      brand: "Apple",
      category: "iPad",
      condition: "new",
      price: 1799,
      oldPrice: 1999,
      warranty: "1 il zəmanət",
      stock: 4,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Pro səviyyəli performans, böyük ekran.",
      fullDescription:
        "iPad Pro yüksək performans istəyənlər üçün premium planşetdir.",
      specifications: { Yaddaş: "256GB", RAM: "8GB", Ekran: '12.9"', Chip: "M2" },
      featured: true,
      popular: true,
      mainImage: images.ipad[1],
      gallery: images.ipad,
      createdAt: "2025-03-05",
    }),
    withDefaults({
      id: 14,
      name: "iPad 9 İşlənmiş",
      slug: "ipad-9-used",
      brand: "Apple",
      category: "iPad",
      condition: "used",
      price: 499,
      oldPrice: 549,
      warranty: "1 il zəmanət",
      stock: 3,
      ram: "3GB",
      storage: "64GB",
      shortDescription: "Təhsil və əyləncə üçün büdcəli işlənmiş iPad.",
      fullDescription:
        "İşlənmiş iPad 9 təhsil və gündəlik istifadə üçün münasib qiymətli seçimdir.",
      specifications: {
        Yaddaş: "64GB",
        RAM: "3GB",
        Ekran: '10.2"',
        Vəziyyət: "Yoxlanılıb",
      },
      featured: false,
      popular: false,
      mainImage: images.ipad[0],
      gallery: images.ipad,
      createdAt: "2025-01-18",
    }),
    withDefaults({
      id: 15,
      name: "MacBook Air M1",
      slug: "macbook-air-m1",
      brand: "Apple",
      category: "MacBook",
      condition: "new",
      price: 1799,
      oldPrice: 1899,
      warranty: "1 il zəmanət",
      stock: 5,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Nazik, sürətli, etibarlı noutbuk.",
      fullDescription:
        "MacBook Air M1 ofis işi, təhsil və yüngül professional istifadə üçün güclü seçimdir.",
      specifications: {
        Yaddaş: "256GB SSD",
        RAM: "8GB",
        Chip: "M1",
        Ekran: '13.3"',
      },
      featured: true,
      popular: true,
      mainImage: images.macbook[0],
      gallery: images.macbook,
      createdAt: "2025-03-12",
    }),
    withDefaults({
      id: 16,
      name: "MacBook Air M2",
      slug: "macbook-air-m2",
      brand: "Apple",
      category: "MacBook",
      condition: "new",
      price: 2299,
      oldPrice: 2499,
      warranty: "1 il zəmanət",
      stock: 4,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Növbəti nəsil performans, uzun batareya.",
      fullDescription:
        "MacBook Air M2 daha güclü performans, uzun batareya ömrü və səssiz işləmə təklif edir.",
      specifications: {
        Yaddaş: "256GB SSD",
        RAM: "8GB",
        Chip: "M2",
        Ekran: '13.6"',
      },
      featured: true,
      popular: true,
      mainImage: images.macbook[1],
      gallery: images.macbook,
      createdAt: "2025-03-20",
    }),
    withDefaults({
      id: 17,
      name: "MacBook Pro 2019 İşlənmiş",
      slug: "macbook-pro-2019-used",
      brand: "Apple",
      category: "MacBook",
      condition: "used",
      price: 1099,
      oldPrice: 1299,
      warranty: "1 il zəmanət",
      stock: 2,
      ram: "16GB",
      storage: "512GB",
      shortDescription: "İş və ofis üçün yoxlanılmış işlənmiş Pro model.",
      fullDescription:
        "İşlənmiş MacBook Pro 2019 ofis, dizayn və gündəlik iş axını üçün yoxlanılmış vəziyyətdədir.",
      specifications: {
        Yaddaş: "512GB SSD",
        RAM: "16GB",
        Chip: "Intel i7",
        Vəziyyət: "Yoxlanılıb",
      },
      featured: false,
      popular: true,
      mainImage: images.macbook[0],
      gallery: images.macbook,
      createdAt: "2025-01-25",
    }),
    withDefaults({
      id: 18,
      name: "MacBook Air 2020 İşlənmiş",
      slug: "macbook-air-2020-used",
      brand: "Apple",
      category: "MacBook",
      condition: "used",
      price: 1199,
      oldPrice: 1299,
      warranty: "1 il zəmanət",
      stock: 3,
      ram: "8GB",
      storage: "256GB",
      shortDescription: "Tələbə və iş üçün etibarlı işlənmiş MacBook Air.",
      fullDescription:
        "İşlənmiş MacBook Air 2020 təmiz vəziyyətdə, gündəlik iş üçün idealdır.",
      specifications: {
        Yaddaş: "256GB SSD",
        RAM: "8GB",
        Chip: "M1",
        Vəziyyət: "Yoxlanılıb",
      },
      featured: false,
      popular: false,
      mainImage: images.macbook[1],
      gallery: images.macbook,
      createdAt: "2025-02-02",
    }),
  ];
  
  export default products;
  
